//************************************************************************************
//**  
//**  File name:     E:\Skola\Mirkoracunari\Trcece svijetlo\trcece_svjetlo.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Sunday, November 05, 2017 15:59:14
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F877
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_30
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 10000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f7a
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f7a);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations


//Variable declarations
#define FCV_TRUE (1)
#define FCV_FALSE (0)



#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations

//U ovom projektu trebamo simulirati trcece svijetlo


void main()
{
	//Initialization
	adcon1 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Gasimo sve led na portu B
	//Output: 255 -> PORTB
	trisb = 0x00;
	portb = (255);

	//Loop
	//Loop: While 1
	while (1)
	{

		//Palimo prvu i zadnju led
		//Output: 126 -> PORTB
		trisb = 0x00;
		portb = (126);

		//Vrijeme za koje svijetle led 
		//Delay: 200 ms
		delay_ms(200);

		//Palimo drugu i sedmu led 
		//Output: 189 -> PORTB
		trisb = 0x00;
		portb = (189);

		//Vrijeme za koje svijetle led 
		//Delay: 200 ms
		delay_ms(200);

		//Palimo trecu i sestu led 
		//Output: 219 -> PORTB
		trisb = 0x00;
		portb = (219);

		//Vrijeme za koje svijetle led 
		//Delay: 200 ms
		delay_ms(200);

		//Palimo cetvrtu i petu led 
		//Output: 231 -> PORTB
		trisb = 0x00;
		portb = (231);

		//Vrijeme za koje svijetle led
		//Delay: 200 ms
		delay_ms(200);

		//Palimo trecu i sestu led 
		//Output: 219 -> PORTB
		trisb = 0x00;
		portb = (219);

		//Vrijeme za koje svijetle led
		//Delay: 500 ms
		delay_ms(255);
		delay_ms(245);

		//Palimo drugu i sedmu led 
		//Output: 189 -> PORTB
		trisb = 0x00;
		portb = (189);

		//Vrijeme za koje svijetle led
		//Delay: 500 ms
		delay_ms(255);
		delay_ms(245);

		//Palimo prvu i zadnju led 
		//Output: 126 -> PORTB
		trisb = 0x00;
		portb = (126);

		//Vrijeme za koje svijetle led 
		//Delay: 500 ms
		delay_ms(255);
		delay_ms(245);


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



